CREATE DATABASE IF NOT EXISTS security;
USE security;

-- DROP TABLE IF EXISTS Stock;
-- DROP TABLE IF EXISTS Category;
-- DROP TABLE IF EXISTS Exchange;

DROP TABLE IF EXISTS StockMetaData;
DROP TABLE IF EXISTS StockData;
DROP TABLE IF EXISTS StockDividend;

CREATE TABLE IF NOT EXISTS Exchange (
  ExchangeId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ExchangeName CHAR(3) NOT NULL,
  PRIMARY KEY (ExchangeId),
  UNIQUE (ExchangeName));

CREATE TABLE IF NOT EXISTS Category (
  CategoryId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CategoryName VARCHAR(50),
  PRIMARY KEY (CategoryId),
  UNIQUE (CategoryName));

CREATE TABLE IF NOT EXISTS Stock (
  StockId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Ticker VARCHAR(10) NOT NULL,
  StockName VARCHAR(50) NOT NULL,
  ExchangeId SMALLINT UNSIGNED NOT NULL,
  CategoryId SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (StockId),
  FOREIGN KEY (ExchangeId) REFERENCES Exchange(ExchangeId),
  FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId),
  CONSTRAINT uc_StockContents UNIQUE (Ticker,StockName));

CREATE TABLE IF NOT EXISTS StockMetaData (
  StockMetaDataId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Founded DATE,
  StockId SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (StockMetaDataId),
  FOREIGN KEY (StockId) REFERENCES Stock(StockId));

-- History Data Tables

CREATE TABLE IF NOT EXISTS StockData (
  StockDataId INT UNSIGNED NOT NULL AUTO_INCREMENT,
  StockId SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (StockDataId),
  FOREIGN KEY (StockId) REFERENCES Stock(StockId));

CREATE TABLE IF NOT EXISTS StockDividend (
  StockDividendId INT UNSIGNED NOT NULL AUTO_INCREMENT,
  StockId SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (StockDividendId),
  FOREIGN KEY (StockId) REFERENCES Stock(StockId));

-- source ~/git/security/sql/security_data.sql
